### ISSUE TITLE
rsvg-convert not found message on ubuntu

### ISSUE THREAD

**Issue by milovanderlinden** [abhishekmukherg/firefoxnotify#14]
When installing on Ubuntu Oneric, I get:

rsvg-convert logo.svg -o src/chrome/content/logo.png --width=32 --keep-aspect-ratio --format=png
make: rsvg-convert: Command not found
make: **\* [src/chrome/content/logo.png] Error 127

Installing librsvg2-bin solves the issue, could you add it to the readme as a dependency?

Thanks

**Comment by phpbbireland** [comment]
Just to confirm your solution worked for too ;)

**Comment by HeIIow2** [comment]
It works if you run into the issue while using pandoc.
