### ISSUE TITLE
Not installable for firefox 3.6pre

### ISSUE THREAD

**Issue by antono** [abhishekmukherg/firefoxnotify#9]
Cannot do it :(

**Comment by abhishekmukherg** [comment]
I was told my extension would be useless for 3.6 since it would have the feature built in. as it should.

**Comment by sigmike** [comment]
it doesn't seem to be the case. many people request the update : https://addons.mozilla.org/en-US/firefox/reviews/display/9622

**Comment by lubosz** [comment]
http://aur.archlinux.org/packages/firefox-extension-firefoxnotify-git/firefox-extension-firefoxnotify-git/firefox-3.6.patch

Please apply this patch. 3.6 is stable.
